apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: default
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          preferred_ip_protocol: ip4
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          headers:
            User-Agent: InfoTerminal-Synthetic/1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.25.0
          args: ["--config.file=/etc/blackbox/blackbox.yml"]
          ports:
            - containerPort: 9115
              name: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
            items:
              - key: blackbox.yml
                path: blackbox.yml
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: default
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: metrics
      port: 9115
      targetPort: metrics
