import { Entity } from '../panels/types';

export const MOCK_ENTITIES: Entity[] = [
  {
    id: '1',
    name: 'John Smith',
    type: 'Person',
    mentions: 156,
    confidence: 0.95,
    firstSeen: '2024-01-15',
    lastSeen: '2024-03-01',
    sources: ['document-1', 'document-5', 'document-12'],
    verified: true,
    description: 'Senior executive at ACME Corporation',
    aliases: ['J. Smith', 'John S.'],
    connections: 23,
    riskScore: 2,
    tags: ['executive', 'finance']
  },
  {
    id: '2',
    name: 'ACME Corporation',
    type: 'Organization',
    mentions: 243,
    confidence: 0.98,
    firstSeen: '2024-01-10',
    lastSeen: '2024-03-02',
    sources: ['document-2', 'document-3', 'document-8', 'document-15'],
    verified: true,
    description: 'Global technology company',
    connections: 45,
    riskScore: 1,
    tags: ['technology', 'public-company']
  },
  {
    id: '3',
    name: 'London',
    type: 'Location',
    mentions: 89,
    confidence: 0.92,
    firstSeen: '2024-01-20',
    lastSeen: '2024-02-28',
    sources: ['document-4', 'document-9'],
    verified: false,
    description: 'Capital city of the United Kingdom',
    connections: 12,
    riskScore: 0,
    tags: ['city', 'europe']
  },
  {
    id: '4',
    name: 'john.smith@acme.com',
    type: 'Email',
    mentions: 67,
    confidence: 0.99,
    firstSeen: '2024-02-01',
    lastSeen: '2024-03-01',
    sources: ['document-1', 'document-6', 'document-11'],
    verified: false,
    connections: 8,
    riskScore: 1,
    tags: ['contact']
  },
  {
    id: '5',
    name: 'acme.com',
    type: 'Domain',
    mentions: 45,
    confidence: 0.87,
    firstSeen: '2024-01-25',
    lastSeen: '2024-02-29',
    sources: ['document-2', 'document-7'],
    verified: true,
    connections: 15,
    riskScore: 0,
    tags: ['website', 'corporate']
  },
  {
    id: '6',
    name: 'suspicious.example.com',
    type: 'Domain',
    mentions: 12,
    confidence: 0.75,
    firstSeen: '2024-02-28',
    lastSeen: '2024-03-01',
    sources: ['document-20'],
    verified: false,
    description: 'Domain flagged for suspicious activity',
    connections: 3,
    riskScore: 8,
    tags: ['suspicious', 'flagged']
  }
];
