version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["deps", "npm"]
  - package-ecosystem: "pip"
    directory: "/services/graph-views"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["deps", "python"]
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "fastapi"
