repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        additional_dependencies: []
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^services/graph-views/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: prettier
        name: prettier (npx, safe paths)
        language: system
        entry: npx
        args: ["-y", "prettier@3.3.3", "--log-level", "warn", "--write"]
        pass_filenames: true
        # Nur noch diese Patterns (entspricht scripts/prettier_safe.list)
        files: |
          (?x)^(
            README\.md|
            docs/.*\.md|
            \.github/.*\.(yml|yaml|json)|
            apps/frontend/.*\.(ts|tsx|js|jsx|json|md|yml|yaml)|
            services/graph-views/.*\.(md|json)
          )$
        exclude: ""
