blockedGlobs:
  - "**/.env"
  - "**/.env.*"
  - "**/*secret*"
  - "**/*secrets*"
  - "**/*credentials*"
  - "**/*key*"
blockedPatterns:
  - "OPENAI_API_KEY="
  - "POSTGRES_PASSWORD="
  - "NEO4J_AUTH="
  - "OPENSEARCH_PASSWORD="
