version: "3.9"
services:
  gateway:
    build: ./services/gateway
    env_file:
      - .env
    environment:
      - PORT=8080
      # Umschalten der Upstreams (Local-Mode nutzt Host-Ports 8611/8612/3417)
      - USE_LOCAL_UPSTREAMS=${USE_LOCAL_UPSTREAMS:-0}
      - SEARCH_TARGET=${SEARCH_TARGET:-}
      - GRAPH_TARGET=${GRAPH_TARGET:-}
      - FLOWISE_TARGET=${FLOWISE_TARGET:-}
      # Security
      - OIDC_ENABLED=${OIDC_ENABLED:-0}
      - OIDC_ISSUER=${OIDC_ISSUER:-}
      - OIDC_AUDIENCE=${OIDC_AUDIENCE:-account}
      - OPA_ENABLED=${OPA_ENABLED:-1}
      - OPA_URL=${OPA_URL:-http://opa:8181/v1/data/access/allow}
      - OPA_AUDIT_URL=${OPA_AUDIT_URL:-}
      # Observability (Services exportieren selbst; Gateway liefert /metrics)
    ports:
      - "8610:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10
