services:
  doc-entities:
    build: ./services/doc-entities
    ports: ["${IT_PORT_DOC_ENTITIES:-8613}:8000"]
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
