services:
  otel-collector:
    image: otel/opentelemetry-collector:0.106.1
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./infra/observability/otel-collector.yaml:/etc/otel/config.yaml:ro
    # untypisch: 3416 (intern bleibt 4317)
    ports: ["3416:4317"]
    profiles: ["obs"]
  loki:
    image: grafana/loki:2.9.8
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./infra/observability/loki/values.yaml:/etc/loki/config.yaml:ro
    # untypisch: 3413
    ports: ["3413:3100"]
    profiles: ["obs"]
  promtail:
    image: grafana/promtail:2.9.8
    volumes:
      - /var/log:/var/log:ro
      - ./infra/observability/promtail/values.yaml:/etc/promtail/config.yaml:ro
    command: ["--config.file=/etc/promtail/config.yaml"]
    profiles: ["obs"]
    depends_on:
      loki:
        condition: service_started
  tempo:
    image: grafana/tempo:2.5.0
    volumes:
      - ./infra/observability/tempo/values.yaml:/etc/tempo/config.yaml:ro
    command: ["-config.file=/etc/tempo/config.yaml"]
    # untypisch: 3414
    ports: ["3414:3200"]
    profiles: ["obs"]
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./infra/observability/prometheus/values.yaml:/etc/prometheus/prometheus.yml:ro
    # untypisch: 3415
    ports: ["3415:9090"]
    profiles: ["obs"]
  grafana:
    image: grafana/grafana:10.4.5
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./deploy/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards:ro
    # untypisch: 3412
    ports: ["3412:3000"]
    profiles: ["obs"]
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      tempo:
        condition: service_started
