services:
  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=7d
    volumes:
      - prometheus-data:/prometheus
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "3412:9090"
    profiles: ["observability"]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "3414:9093"
    profiles: ["observability"]

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./deploy/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3413:3000"
    profiles: ["observability"]
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.4
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./observability/loki-config.yml:/etc/loki/loki.yml:ro
    ports:
      - "3415:3100"
    profiles: ["observability"]

  tempo:
    image: grafana/tempo:2.4.1
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./observability/tempo-config.yml:/etc/tempo/tempo.yml:ro
    ports:
      - "3416:3200"
    profiles: ["observability"]

  promtail:
    image: grafana/promtail:2.9.4
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./observability/promtail-config.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles: ["observability"]
    depends_on:
      - loki

volumes:
  prometheus-data: {}
  grafana-data: {}
