x-runtime-defaults: &runtime_defaults
  security_opt:
    - "no-new-privileges:true"
    - "seccomp=./security/runtime/seccomp/infoterminal-default.json"
    - "apparmor:docker-default"
  cap_drop:
    - ALL
  cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FOWNER
    - NET_BIND_SERVICE
    - SETGID
    - SETUID

services:
  neo4j:
    <<: *runtime_defaults
    image: neo4j:5.22
    container_name: it-neo4j
    environment:
      NEO4J_AUTH: neo4j/test123
      # kleine, konservative Memory-Settings (optional)
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 512m
      NEO4J_server_memory_pagecache_size: 256m
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - it-neo4j-data:/data

networks:
  default:
    internal: true
volumes:
  it-neo4j-data:
    name: it-neo4j-data
