x-runtime-defaults: &runtime_defaults
  security_opt:
    - "no-new-privileges:true"
    - "seccomp=./security/runtime/seccomp/infoterminal-default.json"
    - "apparmor:docker-default"
  cap_drop:
    - ALL
  cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FOWNER
    - NET_BIND_SERVICE
    - SETGID
    - SETUID

services:
  opa:
    <<: *runtime_defaults
    ports:
      - "8651:8181"
    image: openpolicyagent/opa:latest
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=info"
      - "--set=decision_logs.console=true"
      - "/policies"
    volumes:
      - ./services/policy:/policies:ro
    healthcheck:
      test: ["CMD", "opa", "health", "--addr", "http://localhost:8181"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      infoterminal_mesh: {}
      default: {}
      egress: {}
networks:
  infoterminal_mesh:
    external: true
  default:
    internal: true
  egress:
    external: false
