services:
  search-api:
    profiles: ["observability"]
    environment:
      - IT_ENABLE_METRICS=1

  graph-api:
    profiles: ["observability"]
    environment:
      - IT_ENABLE_METRICS=1

  graph-views:
    profiles: ["observability"]
    environment:
      - IT_ENABLE_METRICS=1

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - prometheus-data:/prometheus
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT:-3412}:9090"
    profiles: ["observability"]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "127.0.0.1:${ALERTMANAGER_PORT:-3414}:9093"
    profiles: ["observability"]

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deploy/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./deploy/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "127.0.0.1:${GRAFANA_PORT:-3413}:3000"
    profiles: ["observability"]
    depends_on:
      - prometheus

volumes:
  prometheus-data: {}
  grafana-data: {}
