[project]
name = "openbb-connector"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pandas>=2.2", "requests>=2.31", "psycopg2-binary>=2.9", "python-dotenv>=1.0"
]

[tool.uv]
index-url = "https://pypi.org/simple"
