replicaCount: 1

image:
  repository: ghcr.io/infoterminal/infoterminal
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: http
  annotations: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

strategy:
  type: RollingUpdate

containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP

env: []

envFrom: []

probes:
  liveness:
    enabled: true
    path: /healthz
    port: http
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    enabled: true
    path: /readyz
    port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

resourcesPreset:
  enabled: false
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  labels: {}

secrets:
  enabled: false
  name: ""
  data: {}
  stringData: {}

configMaps: []
  # - name: extra-config
  #   data:
  #     APP_ENV: production

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: infoterminal.local
      paths:
        - path: /
          pathType: Prefix
          servicePort: http
  tls: []
