apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infoterminal-secretstore
  namespace: default
spec:
  provider:
    kubernetes:
      auth:
        serviceAccountRef:
          name: default
      remoteNamespace: secrets
