[project]
name = "gateway"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = "-q --strict-markers --disable-warnings --cov=app --cov-report=term-missing --cov-fail-under=92"
asyncio_mode = "auto"
