server:
  global:
    scrape_interval: 15s
  extraScrapeConfigs:
    - job_name: 'otel-collector'
      static_configs: [{ targets: ['otel-collector.default.svc:9464'] }]
    - job_name: 'python-services'
      kubernetes_sd_configs: [{ role: endpoints }]
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_pod_label_app]
          regex: (search-api|graph-api|gateway)
    - job_name: 'node-exporter'
      static_configs: []
