apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: { name: oauth2-proxy-secret, namespace: edge-auth }
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vault, kind: ClusterSecretStore }
  target:
    name: oauth2-proxy-secret
    creationPolicy: Merge
  data:
    - secretKey: client-id
      remoteRef: { key: edge-auth/oauth2-proxy, property: client-id }
    - secretKey: client-secret
      remoteRef: { key: edge-auth/oauth2-proxy, property: client-secret }
    - secretKey: cookie-secret
      remoteRef: { key: edge-auth/oauth2-proxy, property: cookie-secret }
