apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    mtls/enforce: "strict"
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-strict-mtls
  namespace: default
spec:
  mtls:
    mode: STRICT
