apiVersion: v1
kind: ConfigMap
metadata: { name: prometheus-config, namespace: observability }
data:
  prometheus.yaml: |
    global: { scrape_interval: 15s }
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs: [{ targets: ['otel-collector.observability.svc.cluster.local:8889'] }]
      - job_name: 'dbt-quality'
        static_configs: [{ targets: ['dbt-quality.analytics.svc.cluster.local:9108'] }]

