apiVersion: v1
kind: ConfigMap
metadata: { name: grafana-rule-error-rate, namespace: observability }
data:
  rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: Errors
        folder: "SLO"
        interval: 1m
        rules:
          - uid: error-rate
            title: "High error rate"
            condition: GT
            data:
              - refId: R
                datasourceUid: prometheus
                relativeTimeRange: { from: 300, to: 0 }
                model:
                  expr: 100*sum(rate(spanmetrics_calls_total{service_name="search-api",http_status_code=~"5.."}[5m])) / clamp_min(sum(rate(spanmetrics_calls_total{service_name="search-api"}[5m])), 1e-6)
              - refId: T
                datasourceUid: __expr__
                model: { type: threshold, expression: "2" }
              - refId: GT
                datasourceUid: __expr__
                model: { type: math, expression: "R > T" }
            annotations: { summary: "search-api error rate > 2% (5m)" }
            labels: { severity: "critical", service: "search-api" }

