auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 0
common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
storage_config:
  filesystem:
    chunks_directory: /loki/chunks
    rules_directory: /loki/rules
limits_config:
  retention_period: 168h
