apiVersion: v1
kind: Namespace
metadata:
  name: graph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: graph
spec:
  replicas: 1
  selector:
    matchLabels: { app: neo4j }
  template:
    metadata:
      labels: { app: neo4j }
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.22.0-community
          env:
            - name: NEO4J_AUTH
              value: "neo4j/neo4jpass"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "512m"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "1g"
          ports:
            - containerPort: 7474
            - containerPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: graph
spec:
  type: NodePort
  selector: { app: neo4j }
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      nodePort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
      nodePort: 7687
