kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: infoterminal
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 8081
    hostPort: 8081
    protocol: TCP
  - containerPort: 9000
    hostPort: 9000
    protocol: TCP
  - containerPort: 9200
    hostPort: 9200
    protocol: TCP
  - containerPort: 5432
    hostPort: 5432
    protocol: TCP
