{{- if and .Values.secrets.enabled (or .Values.secrets.data .Values.secrets.stringData) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "infoterminal.fullname" .)) .Values.secrets.name }}
  labels:
    {{- include "infoterminal.labels" . | nindent 4 }}
{{- if .Values.secrets.data }}
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
{{- if .Values.secrets.stringData }}
stringData:
  {{- toYaml .Values.secrets.stringData | nindent 2 }}
{{- end }}
{{- end }}
