apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoterminal-search-api
spec:
  replicas: {{ .Values.searchApi.replicas }}
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
        - name: search-api
          image: {{ .Values.image.registry }}/search-api:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: infoterminal-env
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
