{{- if .Values.autoscaling.enabled }}
{{- $services := dict "gateway" .Values.autoscaling.gateway "frontend" .Values.autoscaling.frontend "feedbackAggregator" .Values.autoscaling.feedbackAggregator "performanceMonitor" .Values.autoscaling.performanceMonitor "cacheManager" .Values.autoscaling.cacheManager "websocketManager" .Values.autoscaling.websocketManager }}
{{- $serviceNames := dict "gateway" "gateway" "frontend" "frontend" "feedbackAggregator" "feedback-aggregator" "performanceMonitor" "performance-monitor" "cacheManager" "cache-manager" "websocketManager" "websocket-manager" }}
{{- range $service, $config := $services }}
{{- if $config }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "infoterminal.fullname" $ }}-{{ get $serviceNames $service }}-hpa
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "infoterminal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ get $serviceNames $service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "infoterminal.fullname" $ }}-{{ get $serviceNames $service }}
  minReplicas: {{ $config.minReplicas }}
  maxReplicas: {{ $config.maxReplicas }}
  metrics:
  {{- if $config.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $config.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $config.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $config.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if $config.metrics }}
  {{- range $config.metrics }}
  - type: {{ .type }}
    {{- if eq .type "Pods" }}
    pods:
      metric:
        name: {{ .pods.metric.name }}
        {{- if .pods.metric.selector }}
        selector:
          {{- toYaml .pods.metric.selector | nindent 10 }}
        {{- end }}
      target:
        type: {{ .pods.target.type }}
        {{- if .pods.target.averageValue }}
        averageValue: {{ .pods.target.averageValue }}
        {{- end }}
    {{- else if eq .type "Object" }}
    object:
      metric:
        name: {{ .object.metric.name }}
        {{- if .object.metric.selector }}
        selector:
          {{- toYaml .object.metric.selector | nindent 10 }}
        {{- end }}
      describedObject:
        apiVersion: {{ .object.describedObject.apiVersion }}
        kind: {{ .object.describedObject.kind }}
        name: {{ .object.describedObject.name }}
      target:
        type: {{ .object.target.type }}
        {{- if .object.target.value }}
        value: {{ .object.target.value }}
        {{- end }}
        {{- if .object.target.averageValue }}
        averageValue: {{ .object.target.averageValue }}
        {{- end }}
    {{- else if eq .type "External" }}
    external:
      metric:
        name: {{ .external.metric.name }}
        {{- if .external.metric.selector }}
        selector:
          {{- toYaml .external.metric.selector | nindent 10 }}
        {{- end }}
      target:
        type: {{ .external.target.type }}
        {{- if .external.target.value }}
        value: {{ .external.target.value }}
        {{- end }}
        {{- if .external.target.averageValue }}
        averageValue: {{ .external.target.averageValue }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if $config.behavior }}
  behavior:
    {{- toYaml $config.behavior | nindent 4 }}
  {{- else }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
