apiVersion: v1
kind: Service
metadata:
  name: infoterminal-search-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: search-api
  ports:
    - port: 8001
      targetPort: 8001
      name: http
