image:
  registry: ghcr.io/ORG/infoterminal
  tag: v0.1.0
  pullPolicy: IfNotPresent

env:
  OPENSEARCH_URL: http://opensearch:9200
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USER: neo4j
  NEO4J_PASS: neo4j
  RERANK_ENABLED: "0"

web:
  replicas: 1
searchApi:
  replicas: 1
graphApi:
  replicas: 1

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  hosts:
    - host: infoterm.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
