apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: search-api
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
