[project]
name = "entity-resolution"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.111", "uvicorn>=0.30", "rapidfuzz>=3.9"]

[tool.uv]
index-url = "https://pypi.org/simple"
