apiVersion: v1
kind: Namespace
metadata:
  name: policy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  namespace: policy
data:
  allow.rego: |
    package access
    default allow = false

    # admins dürfen alles
    allow { input.user.roles[_] == "admin" }

    # analysts: read auf public
    allow {
      input.user.roles[_] == "analyst"
      input.action == "read"
      input.resource.classification == "public"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: policy
spec:
  replicas: 1
  selector:
    matchLabels: { app: opa }
  template:
    metadata:
      labels: { app: opa }
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:0.64.0
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--set=services.bundle.url=http://opa-bundle-server.policy.svc.cluster.local"
            - "--set=bundles.main.resource=/bundles/policy-bundle.tar.gz"
            - "--set=services.audit.url=http://opa-audit-sink.policy.svc.cluster.local"
            - "--set=decision_logs.service=audit"
            - "--set=decision_logs.reporting.min_delay_seconds=5"
            - "--set=decision_logs.reporting.max_delay_seconds=30"
            - "--set=decision_logs.console=false"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: policies
              mountPath: /policies
      volumes:
        - name: policies
          configMap:
            name: opa-policies
---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: policy
spec:
  type: NodePort
  selector: { app: opa }
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      nodePort: 8181
