name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write  # for SARIF upload on push

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend (graph-views)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/graph-views
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: services/graph-views/requirements-dev.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Pytest
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
          PYTHONPATH: ${{ github.workspace }}/services/graph-views
        run: |
          pytest -q

  frontend:
    name: Frontend (apps/frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Lint
        run: npm -w apps/frontend run lint --silent
      - name: Test
        run: npm -w apps/frontend run test --silent -- --reporter=dot

  sbom-source-integrity:
    name: Supply-Chain (SBOM Source)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Generate source SBOMs
        run: python scripts/generate_source_sbom.py
      - name: Verify SBOM artefacts committed
        run: |
          git status --short artifacts/sbom artifacts/compliance || true
          git diff --stat
          git diff --exit-code
      - name: sbom_source_integrity gate
        run: python scripts/check_sbom_source_integrity.py

  gitleaks:
    name: Secrets Scan (gitleaks → SARIF)
    runs-on: ubuntu-latest
    # Nur auf push ausführen, um Fork-PR-Permissions-Probleme zu vermeiden
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Install gitleaks
        run: |
          GITLEAKS_VERSION=8.18.2
          curl -sL https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz \
            | tar -xz
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run gitleaks (always produce SARIF)
        run: |
          gitleaks detect --no-banner --source . \
            --report-format sarif --report-path gitleaks.sarif || true
          # Fallback: leere SARIF, falls Report fehlt
          test -f gitleaks.sarif || echo '{"version":"2.1.0","runs":[]}' > gitleaks.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

  observability:
    name: Observability Baseline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pyyaml
      - name: Generate inventory
        run: python scripts/generate_inventory.py
      - name: Ensure inventory committed
        run: git diff --exit-code
      - name: Observability baseline gate
        run: python scripts/check_observability_baseline.py

  synthetic-smoke:
    name: Synthetic Smoke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate synthetic smoke targets
        run: python scripts/synthetic_smoke.py --validate-only
