name: ci
on: [push, pull_request]
jobs:
  python-node:
    runs-on: ubuntu-latest
    strategy: { fail-fast: false, matrix: { node: [18], py: [3.11] } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.py }} }
      - uses: actions/setup-node@v4
        with: { node-version: ${{ matrix.node }} }
      - name: Python deps
        run: python -m pip install -U pip pytest
      - name: Node deps
        working-directory: apps/frontend
        run: npm ci || npm i
      - name: Frontend unit tests (best-effort)
        working-directory: apps/frontend
        env:
          NEXT_PUBLIC_SEARCH_API: http://127.0.0.1:8401
          NEXT_PUBLIC_GRAPH_API: http://127.0.0.1:8402
          NEXT_PUBLIC_DOCENTITIES_API: http://127.0.0.1:8406
        run: npm test -s || true
      - name: Backend unit tests (best-effort)
        run: |
          pytest -q services/graph-api/tests || true
          pytest -q services/search-api/tests || true
          pytest -q services/doc-entities/tests || true
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OPA tests
        run: |
          curl -sL -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          ./opa test -v policy
  policy-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install conftest
        run: |
          curl -L -o conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.53.0/conftest_0.53.0_Linux_x86_64.tar.gz
          tar -xzf conftest.tar.gz && sudo mv conftest /usr/local/bin/
      - name: Run gate
        run: conftest test -p policy/k8s infra/k8s || true
